- name: playbook
  hosts: all
  become: yes

  tasks:
    - name: Getting Uptime
      command: uptime
    - name: Showing Hostname
      shell: "cat /etc/hostname > ~/output.txt"

    - name: install apache2 
      apt:
        name: apache2
        state: latest
        update_chache: yes

    - name: Start Apache2 Services
      service:
        name: apache2 
         state: started
         enabled: yes
